version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-macroex1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "sam-macroex1"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
